#!/bin/sh
while read PREMISE TABLE
do
	OUT=$(../logos -d '' "$PREMISE" | sed 1d | tr -d '\n')
	[ "$OUT" = "$TABLE" ] && MCH="SUCCESS" || MCH=$"FAILURE\nEXPECTED: $TABLE\nRESULT:   $OUT"
	[ "$1" = "-v" ] &&\
		echo -e "$PREMISE\n$TABLE\n$OUT\n$(head -1 <<< $MCH)\n" ||\
		echo -e "$PREMISE $MCH"
done <<< $(paste -d' ' premises erpelstolz)
